In [1]:
import pandas as pd

import sys
sys.path.append("../src")

from config import url, file_name
from data.load_data import get_data
from data.clean_data import dataset_cleaned

# load row data
df = get_data(url, file_name)

# cleaned subset of the data
cdf = dataset_cleaned(df)

In [2]:
cdf

,MainBranch,Age,Employment,RemoteWork,EdLevel,YearsCode,YearsCodePro,LanguageHaveWorkedWith,DevType,Country,ConvertedCompYearly,ICorPM,WorkExp,Industry
0,Developer,25-34 years old,"Employed, full-time",Remote,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18.0,9.0,HTML/CSS;JavaScript;Python,"Senior Executive (C-Suite, VP, etc.)",United States of America,285000.0,People manager,10.0,"Information Services, IT, Software Development..."
1,Developer,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",27.0,23.0,Bash/Shell (all shells);Go,"Developer, back-end",United States of America,250000.0,Individual contributor,23.0,"Information Services, IT, Software Development..."
2,Developer,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",12.0,7.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,"Developer, front-end",United States of America,156000.0,Individual contributor,7.0,NaN
3,Developer,25-34 years old,NaN,Remote,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6.0,4.0,HTML/CSS;JavaScript;TypeScript,"Developer, full-stack",Philippines,23456.0,Individual contributor,6.0,Other
4,Developer,35-44 years old,"Employed, full-time",Remote,Some college/university study without earning ...,21.0,21.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,"Developer, back-end",United Kingdom of Great Britain and Northern I...,96828.0,Individual contributor,22.0,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47970,Developer,35-44 years old,"Employed, full-time",Remote,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",30.0,24.0,C;C++,"Developer, back-end",Brazil,50719.0,People manager,25.0,"Information Services, IT, Software Development..."
47971,Developer,18-24 years old,NaN,In-person,Some college/university study without earning ...,7.0,2.0,Assembly;Bash/Shell (all shells);C;C#;C++;Java...,"Developer, full-stack",Armenia,16917.0,Individual contributor,3.0,Financial Services
47972,Developer,18-24 years old,"Employed, full-time",Remote,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6.0,2.0,Dart;HTML/CSS;JavaScript;TypeScript,"Developer, mobile",India,15752.0,Individual contributor,2.0,Retail and Consumer Services
47973,Developer,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18.0,9.0,C#;F#;HTML/CSS;JavaScript;SQL;TypeScript,Other (please specify):,France,64254.0,Individual contributor,9.0,Other
47974,Developer,25-34 years old,"Employed, full-time",In-person,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",20.0,9.0,Java;JavaScript;TypeScript,"Developer, full-stack",Greece,61041.0,Individual contributor,9.0,"Information Services, IT, Software Development..."